const TICKET_TYPES = {
  ADULT: 'ADULT',
  CHILD: 'CHILD',
  INFANT: 'INFANT',
};

const MAX_NUMBER_OF_TICKETS_PER_REQUEST = 25;

const TICKET_PRICES = {
  ADULT: 25,
  CHILD: 15,
  INFANT: 0,
};

const MAX_NUMBER_OF_CHILDREN_PER_ADULT = 2;

export {
  TICKET_TYPES,
  MAX_NUMBER_OF_TICKETS_PER_REQUEST,
  TICKET_PRICES,
  MAX_NUMBER_OF_CHILDREN_PER_ADULT,
};
