const TICKET_TYPES = {
  ADULT: 'ADULT',
  CHILD: 'CHILD',
  INFANT: 'INFANT',
};

const MAX_NUMBER_OF_TICKETS_PER_REQUEST = 25;

const TICKET_PRICES = {
  ADULT: 25,
  CHILD: 15,
  INFANT: 0,
};

export { TICKET_TYPES, MAX_NUMBER_OF_TICKETS_PER_REQUEST, TICKET_PRICES };
